name: Pipeline Orchestration

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Build Workflow
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "build.yaml",
              ref: "main"
            });
            console.log("Build workflow triggered:", response.status);

      - name: Wait for Build Workflow to Complete
        uses: actions/github-script@v6
        with:
          script: |
            const { data: runs } = await github.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "build.yaml",
              branch: "main",
              status: "in_progress"
            });

            while (runs.length > 0) {
              console.log("Waiting for build workflow to complete...");
              await new Promise(resolve => setTimeout(resolve, 30000)); // Wait 30 seconds
            }
            console.log("Build workflow completed.");

      - name: Trigger Deploy Workflow
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "deploy.yaml",
              ref: "main"
            });
            console.log("Deploy workflow triggered:", response.status);